### ISSUE TITLE
Score is not calculated correctly

### ISSUE THREAD

**Issue by mariusghitulescu** [Codeinwp/WPPR-Related-Reviews-Widget#13]
Refer to this ticket: http://themeisle.com/forums/topic/cwp-top-products-widget-problem-with-sorting/

Shortly, products with more features will rank higher than those with less features, regardless of the overall score.

@ineagu @selu91

**Comment by selul** [comment]
@contactashish13 can you check here, it's an old issue and i dont if is still happens or not.

**Comment by contactashish13** [comment]
@selul looks like this is ok.

![image](https://cloud.githubusercontent.com/assets/12953439/17205627/61fddfce-54c9-11e6-8c56-5a003f14bcf0.png)

![image](https://cloud.githubusercontent.com/assets/12953439/17205638/6d6e6d1a-54c9-11e6-892d-5d7802c98cb6.png)

![image](https://cloud.githubusercontent.com/assets/12953439/17205652/7a3458e8-54c9-11e6-9677-dde7af157fde.png)
