### ISSUE TITLE
Notificare plugin

### ISSUE THREAD

**Issue by robi09** [Codeinwp/WPPR-Related-Reviews-Widget#5]
Daca pluginul este activat fara pluginul tata, sa se atentioneze userul ca trebuie activat pluginul tata. Pluginul se afla in repo-ul wp.org, cred ca se poate pune tcm activation nu?https://wordpress.org/plugins/wp-product-review/

**Comment by ineagu** [comment]
@robi09 nu prea are rost tgm activation, nu prea are de ce sa il puna lumea fara pluginul tata, o sa fie promovat chiar in el

**Comment by robi09** [comment]
Ok. Eu am incercat sa privesc din asamblu.

On 2/8/2015 4:21 PM, Ionut Neagu wrote:
>
> @robi09 <https://github.com/robi09> nu prea are rost tgm activation, 
> nu prea are de ce sa il puna lumea fara pluginul tata, o sa fie 
> promovat chiar in el
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/Codeinwp/WPPR-Related-Reviews-Widget/issues/5#issuecomment-73412698>.
>

-- 
<http://9pixels.co>
